- predict:
    ds_path: # path to the input file with contigs in fasta format
    nn_weights_path: # folder containing weights for a neural network module
    rf_weights_path: # folder containing weights for a random forest module
    out_path: # where to save predictions
    fragment_length: # 500 or 1000
    n_cpus: # number of cpus you want to use
- prepare_ds_nn:
    path_virus: # path to fasta file with viral sequences
    path_plant: # path to fasta file with plant sequences
    path_bact: # path to fasta file with bacterial sequences
    out_path: # where to save training dataset for neural networks (in hdf5 format)
    fragment_length: # 500 or 1000
    n_cpus: # number of cpus you want to use
    random_seed: # random seed for reshuffling dataset
- prepare_ds_rf:
    path_virus: # path to fasta file with viral sequences
    path_plant: # path to fasta file with plant sequences
    path_bact: # path to fasta file with bacterial sequences
    out_path: # where to save training dataset for RF
    fragment_length: # 500 or 1000
    n_cpus: # number of cpus you want to use
    random_seed: # random seed for reshuffling dataset
- train_nn:
    ds_path: # path to the dataset prepared with prepare_ds_nn.py
    out_path: # where to save weights of the trained neural networks
    fragment_length: # 500 or 1000
    epochs: # Number of epochs for each neural network to train
    random_seed: # random seed for reshuffling of the training dataset
- train_rf:
    nn_weights_path: # path to weights of trained neural networks prepared with train_nn.py
    ds_rf_path: # path to training dataset for RF prepared with prepare_ds_rf.py
    out_path: # where to save weights of the trained RF
    fragment_length: # 500 or 1000
    n_cpus: # number of cpus you want to use
    random_seed: # random seed for reshuffling of the training dataset