- predict:
    ds_path:
    nn_weights_path:
    rf_weights_path:
    out_path:
    fragment_length:
    n_cpus:
- prepare_ds_nn:
    path_virus:
    path_plant:
    path_bact:
    out_path:
    fragment_length:
    n_cpus:
    random_seed:
- prepare_ds_rf:
    path_virus:
    path_plant:
    path_bact:
    out_path:
    fragment_length:
    n_cpus:
    random_seed:
- train_nn:
    ds_path:
    out_path:
    fragment_length:
    epochs:
    random_seed:
- train_rf:
    nn_weights_path:
    ds_rf_path:
    out_path:
    fragment_length:
    n_cpus:
    random_seed: