- predict:
    ds_path:
    weights_path:
    out_path:
    fragment_length:
    n_cpus:

- prepare_ds:
    path_virus:
    path_plant:
    path_bact:
    out_path:
    fragment_length:
    n_cpus:
    random_seed:

- sample_test:
    path_virus:
    path_plant:
    path_bact:
    out_path:
    fragment_length:
    n_cpus:
    random_seed:

- train:
    ds_path:
    out_path:
    test_nn_path:
    fragment_length:
    n_cpus:
    epochs:
    random_seed: