predict:
    test_ds: # path to the input file with contigs in fasta format
    weights: # folder containing weights for NN and RF modules trained on 500 and 1000 fragment lengths
    out_folder: # where to save predictions
    n_cpus: # number of cpus you want to use
    return_viral: # (True/False) Fill in True if you want to recuperate contigs annotated as viral

prepare_ds:
    path_virus: # path to fasta file with viral sequences
    path_plant: # path to fasta file with plant sequences
    path_bact: # path to fasta file with bacterial sequences
    out_path: # where to save training dataset for neural networks (in hdf5 format)
    n_cpus: # number of cpus you want to use
    random_seed: # random seed for reshuffling dataset

train:
    ds_path: # path to the dataset prepared with prepare_ds_nn.py
    out_path: # where to save weights of the trained neural networks
    epochs: # Number of epochs for each neural network to train
    n_cpus: # number of cpus you want to use
    random_seed: # random seed for reshuffling of the training dataset

prepare_ds_complex:
    path_virus: # path to fasta file with viral sequences
    path_plant_genome: # path to fasta file with plant genome sequences
    path_plant_chl: # path to fasta file with plant chloroplast sequence
    path_plant_cds: # path to fasta file with plant CDS sequences
    path_bact: # path to fasta file with bacterial sequences
    out_path: # where to save training dataset for neural networks (in hdf5 format)
    n_cpus: # number of cpus you want to use
    random_seed: # random seed for reshuffling dataset