prepare_ds:
    path_virus: test_installation/viruses.fasta
    path_plant: test_installation/host.fasta
    path_bact: test_installation/bacteria.fasta
    out_path: test_installation_out
    n_cpus: 10
    random_seed: 5

train:
    ds_path: test_installation_out
    out_path: test_installation_out
    epochs: 1
    n_cpus: 10
    random_seed: 5

predict:
    test_ds: test_installation/viruses.fasta
    weights: test_installation_out
    out_folder: test_installation_out
    n_cpus: 1
    return_viral: True